version: '3'
services:
  mosquitto:
    container_name: "mosquitto"
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  influxdb:
    container_name: "influxdb"
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb2
    restart: always

  grafana:
    container_name: "grafana"
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always

  mqttbridge:
    container_name: "mqttbridge"
    build: ./mqttBridge
    environment:
      - INFLUX_TOKEN=*****
      - INFLUX_ORG=*****
      - INFLUX_BUCKET=*****
      - MQTT_TOPIC=*****
      - MQTT_USER=guest
      - MQTT_PASS=*****
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - "mosquitto"
      - "influxdb"
